config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users
  root 'users#index'

  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :likes, only: [:create]
      resources :comments, only: [:create, :new, :destroy]
    end
  end


  namespace :api, defaults: { format: :json } do
    resources :posts, only: [:index] do
      resources :comments, only: [:create, :index]
    end
  end
  
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
    user ||= User.new

    if user.admin?
      can :manage, :all
    else
      can :manage, Post, author_id: user.id
      can :manage, Comment, author_id: user.id
      can :read, :all
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post
  after_save :update_total_comment
  after_destroy :update_total_comment

  def update_total_comment
    post.update(comments_counter: post.comments.all.length)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  after_save :update_total_likes

  def update_total_likes
    post.update(likes_counter: post.likes.all.length)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :comments, foreign_key: :post_id, dependent: :delete_all
  has_many :likes, foreign_key: :post_id, dependent: :delete_all

  after_save :update_total_posts

  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :title, presence: true, allow_blank: false, length: { maximum: 250 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def last_five_comments
    comments.includes(:author).order(created_at: :desc).limit(5)
  end

  private

  def update_total_posts
    author.update(posts_counter: author.posts.all.length)
  end
end

app/models/user.rb
class User < ApplicationRecord
  include Devise::JWT::RevocationStrategies::JTIMatcher
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable,
         :jwt_authenticatable, jwt_revocation_strategy: self

  has_many :comments, foreign_key: :author_id, dependent: :destroy
  has_many :posts, foreign_key: :author_id, dependent: :destroy
  has_many :likes, foreign_key: :author_id, dependent: :destroy

  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :name, presence: true, allow_blank: false

  def recent_post
    posts.order(created_at: :desc).limit(3)
  end

  def admin?
    role == 'admin'
  end
end

app/controllers/api/comments_controller.rb
class Api::CommentsController < ApplicationController
  load_and_authorize_resource

  def index
    @comments = Comment.where({ post_id: params[:post_id] }).order('created_at')
    render json: { success: true, data: { comments: @comments } }
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(text: comment_params[:text], user: current_user)

    if @comment.save
      render json: { success: true, data: { comment: @comment } }, status: :created
    else
      render json: { success: false, errors: @comment.errors }, status: :bad_request
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/api/posts_controller.rb
class Api::PostsController < ApplicationController
  load_and_authorize_resource

  def index
    @posts = Post.all.order('created_at')
    render json: { success: true, data: { posts: @posts } }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery prepend: true
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource

  def new
    current_user
  end

  def create
    @comment = current_user.comments.new(comment_params)
    @comment.post_id = params[:post_id]

    if @comment.save
      redirect_to user_post_path(current_user, @comment.post)
    else
      render :create
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @post = Post.find(@comment.post_id)

    @comment.destroy
    redirect_to user_post_url(current_user, @comment.post), notice: 'Comment was successfully destroyed.'
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = current_user.likes.new
    @like.post_id = like_params

    if @like.save
      redirect_to user_post_path(current_user, @like.post)
    else
      render :create
    end
  end

  private

  def like_params
    params[:post_id]
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource

  def index
    @posts = User.find(params[:user_id])
  end

  def show
    @post = Post.find(params[:id])
    @userposts = @post.comments.includes(:author, :post)
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)

    if @post.save
      redirect_to user_post_path(current_user, @post)
    else
      render :new
    end
  end

  def destroy
    post = Post.find(params[:id])
    user = User.find(post.author_id)
    post.destroy
    user.posts_counter -= 1
    user.save
    redirect_to user_url(user)
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/new.html.erb
<%= form_with model: Comment, url: user_post_comments_path do |f| %>
  <div>
    <%= f.label 'Add comment' %> <br>
    <%= f.text_area :text, required: true %>
  </div>

  <div> 
    <%= f.submit "Comment" %>
  </div>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Stoupignan</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <h1>Welcome to The Stoupignan Blog!</h1>

    <section class='links_container no_button_style border position_top_right'>
      <span class=''>
        <%= link_to 'Home', root_path %>
      </span>
    
      <%if user_signed_in? %>
        <%= button_to "Sign Out", destroy_user_session_path, method: :delete %>
      <% end %>
      
    </section>

    <%= notice %>
    <%= alert %>
    
    <%= yield %>

    

  
    <footer>Thanks for using The Blog App!</footer>
  </body>
</html>

app/views/posts/index.html.erb
<h1 class="title_page"> Index Posts </h1>

<section class="section_container container">
  <div class="container_photo border">
    <img src='<%= @posts.photo %>' alt='User photo' class="user_photo">
  </div>

  <div class="user_data_container border">
    <h2 class="user_name"><%= @posts.name %></h2>
    <h2 class="post_counter">Number of posts: <%= @posts.posts_counter %></h2>
  </div>
</section>

<% @posts.posts.each_with_index do |post, index| %>

  <%= link_to user_post_path(post.author_id, post) do %>

    <div class="general_container margin_10px">

      <div class="border">
        <h3>Post: <%= index + 1 %></h3>
        <p><%= post.text %></p>

        <div class="display_flex">
          <p>Likes: <%= post.likes_counter %> Comments: <%= post.comments_counter %></p>
        </div>

      </div>

      <div class="border">
        <% post.last_five_comments.each do |comments|%>
          <p><%= comments.author.name %>:<%= comments.text %></p>
        <% end %>
      </div>

    <div>

  <% end %>

<% end %>
  
<%= link_to new_user_post_path do %>
  <span class="border">Add new post</span>
<% end %>

<%= link_to new_user_post_path do %>
  <button>Pagination</button>
<% end %>

app/views/posts/new.html.erb
<h2>Add Post</h2>

<%= form_with model: @post, url: user_posts_path do |form| %>

  <section class="">
    <div>
      <%= form.label :title %>
      <%= form.text_field :title, required: true %>
    </div>

    <div>
      <%= form.label :text %>
      <%= form.text_area :text, required: true %>
    </div>

    <%= form.submit %>
  </section>

<% end %>

<span class="border margin_10px">
  <%= link_to 'Exit here', users_path %>
</span>

app/views/posts/show.html.erb
  <section class="border container margin_10px padding_10px flex_direction_column">
    <div class="">
      <h3>"<%= @post.title %>" by <%= @post.author.name %></h2>
      <p class="display_flex">Comments: <%= @post.comments_counter %> Likes: <%= @post.likes_counter %></p>
    </div>

    <p class=""><%= @post.text %></p>

    <%= render "shared/add_like"%>
  
  </section>
  
  <section class="border container margin_10px padding_10px flex_direction_column">
    <% @userposts.each do |comment|%>
      <p><%= comment.author.name %>: <%= comment.text %></p>

      <div class=''>
        <% if can? :destroy, comment %>
          <%= button_to "Delete comment", user_post_comment_path(comment.author, comment.post, comment), method: :delete %>
        <% end %>
      </div>

    <% end %> 
  </section>

  <section class='no_button_style border links_container position_bottom_right'>
 
    <div >
        <%= render "shared/add_comment"%>
    </div>

    <% if can? :destroy, @post %>
      <div class='border background_red'>
          <%= button_to "Delete Post", user_post_path(@post.author, @post), method: :delete %>
      </div>
    <% end %>

  </section>



  

app/views/shared/_add_comment.html.erb
<%= link_to new_user_post_comment_path(@post.author, @post) do %>
  <span class="border background_blue">Add new comment</span>
<% end %>

app/views/shared/_add_like.html.erb
<div class=''>
  <%= form_with model: Like, url: user_post_likes_path(@post.author, @post) do |f| %>
    <%= f.submit 'Like Post' %>
  <% end %>
</div>

app/views/users/index.html.erb
<h1 class="title_page">All users list</h1>

<% @users.each do |user| %>

  <section class="section_container">
    <%= link_to user_path(user.id) do %>
    
      <article class="container group">

        <div class="container_photo border">
          <img src='<%= user.photo %>' alt='User photo' class="user_photo">
        </div>

        <div class="user_data_container border">
          <h2 class="user_name"><%= user.name %></h2>
          <h4 class="post_counter">Number of posts: <%= user.posts_counter %></h4>
        </div>

      </article>
      
    <% end %>
  </section>

<% end %>

app/views/users/show.html.erb
  <section class="container margin_10px padding_10px">
    <div class="border container_photo">
      <img src='<%= @user.photo %>' alt='User photo' class="user_photo">
    </div>

    <div class="border user_data_container">
      <h2 class="user_name"><%= @user.name %></h2>
      <h2 class="post_counter">Number of posts: <%= @user.posts_counter %></h2>
    </div>
  </section>

  <section class="border general_container margin_10px padding_10px">
    <h3>Bio</h3>
    <p><%= @user.bio %></p>
  </section>

  <% @user.recent_post.each_with_index do |post, index| %>

    <div class="border general_container margin_10px padding_10px group"> 
      <h3>Post: #<%= index + 1 %></h3>
      <p><%= post.text %></p>
      <div class=" display_flex">
        <p>Likes: <%= post.likes_counter %> Comments: <%= post.comments_counter %></p>
      </div>
    </div>

  <% end %>

  <%= link_to user_posts_path(@user) do %>
    <button type="button" class="button_post margin_10px">See all posts</button>
  <% end %>